version: '3.7'
services:
  app:
    image: node:16
    working_dir: /app
    tty: true
    command: bash
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./node_modules:/app/node_modules
      - ./src:/app/src
